on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # v0.0.1

name: release

jobs:
  create_release:
    permissions: write-all
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
